# STEP 1: Base Image
FROM node:18

# STEP 2: Set working directory
WORKDIR /app

# STEP 3: Copy package files
COPY package*.json ./

# STEP 4: Install dependencies
RUN npm install

# STEP 5: Copy source code
COPY . .

# STEP 6: Expose app port
EXPOSE 3001

# STEP 7: Start the app
CMD ["npm", "start"]
